### ISSUE TITLE
update code

### ISSUE THREAD

**Issue by WMAL** [stacefauske/bodhibuilder#6]
First many thanks for this awesome tool I use it to build linux kodachi, I have made custom changes that I would love to share with others please update the code to reflect what is on source forge so I can contribute to the next 5.1.9  release

**Comment by stacefauske** [comment]
Do you have code for version 2.18.x? Because this issue is against version 2.1.x.

I see you have forked this version, but it will not work with Ubuntu 18.04. If you would fork bodhibuilder v2.18.x, I will definitely take a look at your changes. (Also, if the issue is indeed against 2.18.x, please close this issue and open a new one against 2.18.x.)

Thanks!

**Comment by WMAL** [comment]
Oh my mistake I got it now thx :)

**Comment by WMAL** [comment]
Changes made on my fork see what suites and feel free to copy :) 
You have made life easier for a lot of people when it comes to remastering Ubuntu Thank you again
